/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.Dao.EnvioDao;
import Controlador.ListaDoble.ListaDoble;
import Controlador.Utiles;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author Sebastian
 */
public class FrmRegistroPaqueteCliente extends javax.swing.JDialog {

    /**
     * Creates new form FrmRegistroPaqueteCliente
     */
    private EnvioDao ed = new EnvioDao();
    
    
    public FrmRegistroPaqueteCliente(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblfechenvio.setText("" + LocalDate.now());
        limpiar();
    }
    
    private void limpiar(){
        ed.setEnvio(null);
        Utiles.cargarComboPrioridades(cbxpriori);
        
    }
    
    private void guardarP(){
        try {
            limpiar();
            ed.getEnvio().setEstado("pendiente");
            ed.getEnvio().setHist_entrega(new ListaDoble());
            ed.getEnvio().setPrecio(0.0);
            ed.getEnvio().setPrioridad(Utiles.obtenerPrioridades(cbxpriori));
            ed.getEnvio().getPaquete().setContenido(new ListaDoble());
            ed.getEnvio().getPaquete().getDestinatario().setNombre(txtnomDest.getText());
            ed.getEnvio().getPaquete().getDestinatario().setCi_ruc(txtci_rucDest.getText());
            ed.getEnvio().getPaquete().getDestinatario().setCiudad(txtciuDest.getText());
            ed.getEnvio().getPaquete().getDestinatario().setDireccion(txtdirDest.getText());
            ed.getEnvio().getPaquete().getDestinatario().setTelefono(txttelfDest.getText());
            ed.getEnvio().getPaquete().getRemitente().setNombre(txtnomRem.getText());
            ed.getEnvio().getPaquete().getRemitente().setCi_ruc(txtci_rucRem.getText());
            ed.getEnvio().getPaquete().getRemitente().setCiudad(txtciuRem.getText());
            ed.getEnvio().getPaquete().getRemitente().setDireccion(txtdirRem.getText());
            ed.getEnvio().getPaquete().getRemitente().setTelefono(txttefRem.getText());
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String fecha = df.format(txtfechentrega.getText());
            ed.getEnvio().getPaquete().setFecha_entrega(Date.valueOf(fecha));
            ed.getEnvio().getPaquete().setFecha_envio(Date.valueOf(lblfechenvio.getText()));
            ed.getEnvio().getPaquete().setFragil(chbxfragil.getVerifyInputWhenFocusTarget());
            ed.getEnvio().getPaquete().setPeso(Double.parseDouble(txtpeso.getText()));
            ed.guardar();
            ed.getEnvio().setPaquete(ed.getEnvio().getPaquete());
            ed.getEnvio().getPaquete().setDestinatario(ed.getEnvio().getPaquete().getDestinatario());
            ed.getEnvio().getPaquete().setRemitente(ed.getEnvio().getPaquete().getRemitente());
            //ed.getEnvio().getPaquete().getDestinatario()
            if (!ed.guardarEnvioLD()) {
                JOptionPane.showMessageDialog(null, "Se ha guardado paquete al envio");
                //scargarTablaT(null);
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "No se ha guardado paquete al envio");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos erroneos: " + e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnagregarPaq = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnomDest = new javax.swing.JTextField();
        txtci_rucDest = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txttelfDest = new javax.swing.JTextField();
        txtciuDest = new javax.swing.JTextField();
        txtdirDest = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtpeso = new javax.swing.JTextField();
        txtfechentrega = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbxpriori = new javax.swing.JComboBox<>();
        chbxfragil = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        lblfechenvio = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtdirRem = new javax.swing.JTextField();
        txtci_rucRem = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txttefRem = new javax.swing.JTextField();
        txtnomRem = new javax.swing.JTextField();
        txtciuRem = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("R E G I S T R O   P A Q U E T E   D E   C L I E N T E");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(360, 30, 290, 14);

        btnagregarPaq.setText("AGREGAR PAQUETE");
        btnagregarPaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarPaqActionPerformed(evt);
            }
        });
        jPanel1.add(btnagregarPaq);
        btnagregarPaq.setBounds(420, 500, 150, 23);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("REGISTRO DEL DESTINATARIO"));
        jPanel2.setLayout(null);

        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 40, 70, 14);

        jLabel3.setText("CI/RUC:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 80, 70, 14);
        jPanel2.add(txtnomDest);
        txtnomDest.setBounds(140, 40, 250, 20);
        jPanel2.add(txtci_rucDest);
        txtci_rucDest.setBounds(140, 80, 250, 20);

        jLabel4.setText("Telefono:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 120, 60, 14);

        jLabel5.setText("Ciudad:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 160, 41, 14);

        jLabel6.setText("Direccion:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 200, 70, 14);
        jPanel2.add(txttelfDest);
        txttelfDest.setBounds(140, 120, 250, 20);
        jPanel2.add(txtciuDest);
        txtciuDest.setBounds(140, 160, 250, 20);
        jPanel2.add(txtdirDest);
        txtdirDest.setBounds(140, 200, 250, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 70, 480, 240);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("REGISTRO PAQUETE CLIENTE"));
        jPanel3.setLayout(null);

        jLabel8.setText("Peso (Kg):");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(30, 40, 83, 14);

        jLabel9.setText("Fragilidad:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(440, 90, 83, 14);

        jLabel10.setText("Fecha de envio:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(440, 40, 90, 14);
        jPanel3.add(txtpeso);
        txtpeso.setBounds(150, 40, 260, 20);
        jPanel3.add(txtfechentrega);
        txtfechentrega.setBounds(150, 90, 260, 20);

        jLabel11.setText("Prioridad:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(740, 60, 60, 14);

        jPanel3.add(cbxpriori);
        cbxpriori.setBounds(840, 60, 120, 20);

        chbxfragil.setText("Es Fragil");
        jPanel3.add(chbxfragil);
        chbxfragil.setBounds(530, 90, 85, 23);

        jLabel7.setText("Fecha de Entrega:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(30, 90, 89, 14);
        jPanel3.add(lblfechenvio);
        lblfechenvio.setBounds(540, 40, 170, 20);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 340, 1010, 140);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("REGISTRO DE REMITENTE"));
        jPanel4.setLayout(null);
        jPanel4.add(txtdirRem);
        txtdirRem.setBounds(160, 200, 250, 20);
        jPanel4.add(txtci_rucRem);
        txtci_rucRem.setBounds(160, 80, 250, 20);

        jLabel17.setText("Direccion:");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(40, 200, 70, 14);
        jPanel4.add(txttefRem);
        txttefRem.setBounds(160, 120, 250, 20);
        jPanel4.add(txtnomRem);
        txtnomRem.setBounds(160, 40, 250, 20);
        jPanel4.add(txtciuRem);
        txtciuRem.setBounds(160, 160, 250, 20);

        jLabel16.setText("Ciudad:");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(40, 160, 41, 14);

        jLabel13.setText("Nombre:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(40, 40, 70, 14);

        jLabel14.setText("CI/RUC:");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(40, 80, 80, 14);

        jLabel15.setText("Telefono:");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(40, 120, 60, 14);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(530, 70, 490, 240);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarPaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarPaqActionPerformed
        // TODO add your handling code here:
        guardarP();
        new RegistroEnvios().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnagregarPaqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroPaqueteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroPaqueteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroPaqueteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroPaqueteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmRegistroPaqueteCliente dialog = new FrmRegistroPaqueteCliente(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregarPaq;
    private javax.swing.JComboBox<String> cbxpriori;
    private javax.swing.JCheckBox chbxfragil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblfechenvio;
    private javax.swing.JTextField txtci_rucDest;
    private javax.swing.JTextField txtci_rucRem;
    private javax.swing.JTextField txtciuDest;
    private javax.swing.JTextField txtciuRem;
    private javax.swing.JTextField txtdirDest;
    private javax.swing.JTextField txtdirRem;
    private javax.swing.JTextField txtfechentrega;
    private javax.swing.JTextField txtnomDest;
    private javax.swing.JTextField txtnomRem;
    private javax.swing.JTextField txtpeso;
    private javax.swing.JTextField txttefRem;
    private javax.swing.JTextField txttelfDest;
    // End of variables declaration//GEN-END:variables
}
